BeerOverflow/BeerOverflow.WebFinal/Controllers/BeersController.cs
using BeerOverflow.Services.Contracts;
using BeerOverflow.Web.Models;
using BeerOverflow.Web.ViewModelMappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Web.Controllers
{
    public class BeersController : Controller
    {
        private readonly IBeerService beerService;
        private readonly IStyleService styleService;
        private readonly IBreweryService breweryService;

        public BeersController(IBeerService beerService, IStyleService styleService, IBreweryService breweryService)
        {
            this.beerService = beerService ?? throw new ArgumentNullException(nameof(beerService));
            this.styleService = styleService ?? throw new ArgumentNullException(nameof(styleService));
            this.breweryService = breweryService ?? throw new ArgumentNullException(nameof(breweryService));
        }

        // GET: BeersController
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> ListUnlisted()
        {
            // Get all beers
            var beers = new List<BeerViewModel>();

            var allBeers = await this.beerService.RetrieveAllAsync();
            beers = allBeers
                .Where(b => b.IsUnlisted)
                .Select(b => new BeerViewModel(b))
                .OrderBy(b => b.Name)
                .ToList();

            var beerSearchModel = await LoadBeerSearchViewModel(beers);

            return View(beerSearchModel);
        }

        [HttpGet]
        public async Task<ActionResult> Search()
        {
            // Get all beers
            var beers = new List<BeerViewModel>();

            var allBeers = await this.beerService.RetrieveAllAsync();
            beers = allBeers
                .Where(b => !b.IsUnlisted)
                .Select(b => new BeerViewModel(b))
                .OrderBy(b => b.Name)
                .ToList();

            var beerSearchModel = await LoadBeerSearchViewModel(beers, 1);
            beerSearchModel.SortBy = "name";
            beerSearchModel.SortBy = "name";

            return View(beerSearchModel);
        }

        [HttpPost]
        public async Task<ActionResult> Search(BeerSearchViewModel model, int page = 1)
        {
            // Get all beers
            var beers = new List<BeerViewModel>();
            var filteredBeers = await this.beerService.SearchAsync(model.Name, model.StyleName, model.SortBy);
            beers = filteredBeers
                .Where(b => !b.IsUnlisted)
                .Select(b => new BeerViewModel(b))
                .ToList();

            var beerSearchModel = await LoadBeerSearchViewModel(beers, page);
            beerSearchModel.Name = model.Name;
            beerSearchModel.StyleName = model.StyleName;
            beerSearchModel.SortBy = model.SortBy;

            return View(beerSearchModel);
        }

        [HttpGet]
        public async Task<ActionResult> SearchPage(int page, string searchName, string styleName, string sortBy)
        {
            // Get all beers
            var filteredBeers = await this.beerService.SearchAsync(searchName, styleName, sortBy);
            var beers = filteredBeers
                .Where(b => !b.IsUnlisted)
                .Select(b => new BeerViewModel(b));

            var beerSearchViewModel = await LoadBeerSearchViewModel(beers, page);
            beerSearchViewModel.Name = searchName;
            beerSearchViewModel.StyleName = styleName;
            beerSearchViewModel.SortBy = sortBy;

            return View(beerSearchViewModel);
        }

        // GET: BeersController/Details/id
        [HttpGet]
        public async Task<ActionResult> Details(Guid id)
        {
            var beer = await this.beerService.RetrieveByIdAsync(id);

            var bdvm = new BeerDetailsViewModel
            {
                Beer = new BeerViewModel(beer)
            };

            return View(bdvm);
        }

        // GET: BeersController/Create
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var breweries = await this.breweryService.RetrieveAllAsync();
            ViewBag.Breweries = breweries
                .Select(br => new BreweryViewModel(br));

            var styles = await this.styleService.RetrieveAllAsync();
            ViewBag.Styles = styles
                .Select(s => new StyleViewModel(s));

            return View();
        }

        // POST: BeersController/Create
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(BeerViewModel item)
        {
            try
            {
                var beer = await this.beerService.CreateAsync(item.GetDTO());
                return RedirectToAction(nameof(Search));
            }
            catch
            {
                return View();
            }
        }

        // GET: BeersController/Edit/id
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Edit(Guid id)
        {
            var breweries = await this.breweryService.RetrieveAllAsync();
            ViewBag.Breweries = breweries
                .Select(br => new BreweryViewModel(br));

            var styles = await this.styleService.RetrieveAllAsync();
            ViewBag.Styles = styles
                .Select(s => new StyleViewModel(s));

            var dto = await this.beerService.RetrieveByIdAsync(id);
            var vm = new BeerViewModel(dto);

            return View(vm);
        }

        // POST: BeersController/Edit/id
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Edit(Guid id, BeerViewModel model)
        {
            try
            {
                var result = await this.beerService.UpdateAsync(id, model.GetDTO());
                return RedirectToAction(nameof(Search));
            }
            catch
            {
                return View();
            }
        }

        // GET: BeersController/Delete/id
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(Guid id)
        {
            try
            {
                var result = await this.beerService.DeleteAsync(id);
                return RedirectToAction(nameof(Search));
            }
            catch
            {
                return View();
            }
        }

        private async Task<BeerSearchViewModel> LoadBeerSearchViewModel(IEnumerable<BeerViewModel> beers, int page = 1)
        {
            var beerSearchModel = new BeerSearchViewModel();
            beerSearchModel.pageCount = beers.Count() % 12 == 0 ? beers.Count() / 12 : (beers.Count() / 12) + 1;

            // Load data into Search Form
            beerSearchModel.Beers = beers.Skip((page - 1) * 12).Take(12).ToList();

            var styles = await this.styleService.RetrieveAllAsync();
            var styleNames = styles
                .Select(s => s.Name)
                .ToHashSet();

            ViewBag.message = styleNames;

            return beerSearchModel;
        }
    }
}

BeerOverflow/BeerOverflow.WebFinal/Controllers/BreweriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflow.Services.Contracts;
using BeerOverflow.Web.Models;
using BeerOverflow.Web.ViewModelMappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BeerOverflow.Web.Controllers
{
    public class BreweriesController : Controller
    {
        private IBreweryService breweryService;
        private readonly ICountryService countryService;

        public BreweriesController(IBreweryService breweryService, ICountryService countryService)
        {
            this.breweryService = breweryService ?? throw new ArgumentNullException(nameof(breweryService));
            this.countryService = countryService ?? throw new ArgumentNullException(nameof(countryService));
        }

        // GET: BreweriesController
        public async Task<ActionResult> List()
        {
            var result = await this.breweryService.RetrieveAllAsync();
            var breweries = result.Select(br => new BreweryViewModel(br));

            return View(breweries);
        }

        // GET: BreweriesController/Create
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var countries = await this.countryService.RetrieveAllAsync();
            ViewBag.Countries = countries
                .Select(c => new CountryViewModel(c));

            return View();
        }

        // POST: BreweriesController/Create
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(BreweryViewModel item)
        {
            try
            {
                var brewery = await this.breweryService.CreateAsync(item.GetDTO());
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }

        // GET: BreweriesController/Delete/id
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Delete(Guid id)
        {
            try
            {
                var result = await this.breweryService.DeleteAsync(id);
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }
    }
}

BeerOverflow/BeerOverflow.WebFinal/Controllers/CountriesController.cs
using BeerOverflow.Services.Contracts;
using BeerOverflow.Web.Models;
using BeerOverflow.Web.ViewModelMappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace BeerOverflow.Web.Controllers
{
    public class CountriesController : Controller
    {
        private readonly ICountryService countryService;

        public CountriesController(ICountryService countryService)
        {
            this.countryService = countryService ?? throw new ArgumentNullException(nameof(countryService));
        }
        // GET: CountriesController
        public async Task<ActionResult> List()
        {
            var result = await this.countryService.RetrieveAllAsync();
            var countries = result.Select(c => new CountryViewModel(c));

            return View(countries);
        }

        // GET: CountriesController/Create
        [HttpGet]
        [Authorize]
        public async Task<ActionResult> Create()
        {
            var countries = await this.countryService.RetrieveAllAsync();
            ViewBag.Countries = countries
                .Select(c => new CountryViewModel(c));

            return View();
        }

        // POST: CountriesController/Create
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(CountryViewModel item)
        {
            try
            {
                var country = await this.countryService.CreateAsync(item.GetDTO());
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }
    }
}

BeerOverflow/BeerOverflow.WebFinal/Controllers/StylesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BeerOverflow.Services.Contracts;
using BeerOverflow.Web.Models;
using BeerOverflow.Web.ViewModelMappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BeerOverflow.Web.Controllers
{
    public class StylesController : Controller
    {
        private readonly IStyleService styleService;

        public StylesController(IStyleService styleService)
        {
            this.styleService = styleService ?? throw new ArgumentNullException(nameof(styleService));
        }

        // GET: StylesController
        [HttpGet]
        public async Task<ActionResult> List()
        {
            var stlyleDTOs = await this.styleService.RetrieveAllAsync();

            var styles = stlyleDTOs
                .Select(s => new StyleViewModel(s))
                .ToList();

            return View(styles);
        }

        // GET: StylesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: StylesController/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            var styles = await this.styleService.RetrieveAllAsync();
            ViewBag.Styles = styles
                .Select(s => new StyleViewModel(s));

            return View();
        }

        // POST: StylesController/Create
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Create(StyleViewModel item)
        {
            try
            {
                var style = await this.styleService.CreateAsync(item.GetDTO());
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }

        // GET: StylesController/Edit/id
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: StylesController/Edit/id
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }

        // GET: StylesController/Delete/id
        [Authorize]
        public ActionResult Delete(int id) // TODO: Not in assignment so not added as functionality
        {
            return View();
        }

        // POST: StylesController/Delete/id
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(List));
            }
            catch
            {
                return View();
            }
        }
    }
}

BeerOverflow/BeerOverflow.WebFinal/Views/Shared/_CarouselPartial.cshtml
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/carousel/carousel1.jpg" data-color="firebrick" alt="Second Image">
            <div class="carousel-caption d-md-block">
                <div class="caption">
                    <div class="holder">
                        <strong class="title">Original taste • since 1982</strong> <span>Premiucccxcvm Quality</span>
                        <h1>Treats, Fun Memories<b>&amp;</b>Love</h1>
                        <strong class="title-2">For Friends Saya</strong>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/carousel/carousel2.jpg" data-color="firebrick" alt="Second Image">
            <div class="carousel-caption d-md-block">
                <div class="caption">
                    <div class="holder">
                        <strong class="title">Original taste <br> since 1982</strong> <span>Premiucccxcvm Quality</span>
                        <h1>Treats, Fun Memories<b>&amp;</b>Love</h1>
                        <strong class="title-2">For Friends Saya</strong>
                    </div>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="~/images/carousel/carousel3.jpg" data-color="violet" alt="Third Image">
            <div class="carousel-caption d-md-block">
                <div class="caption">
                    <div class="holder">
                        <strong class="title">Original taste • since 1982</strong> <span>Premiucccxcvm Quality</span>
                        <h1>Treats, Fun Memories<b>&amp;</b>Love</h1>
                        <strong class="title-2">For Friends Saya</strong>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Controls -->
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

BeerOverflow/BeerOverflow.WebFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NineBeers</title>
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand cursive-h1" asp-area="" asp-controller="Home" asp-action="Index">NineBeers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Beers" asp-action="Search">Beers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Styles" asp-action="List">Styles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Breweries" asp-action="List">Breweries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Countries" asp-action="List">Countries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
        <div class="container footer-bg">
            &copy; 2020 - BeerOverflow Team9 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BeerOverflow/BeerOverflow.WebFinal/Views/Shared/_ManageMenuPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using BeerOverflow.Models

@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager


<ul class="nav nav-pills flex-column">
    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="Manage">Profile</a></li>
    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="DrankList">DrankList</a></li>
    <li class="nav-item"><a class="nav-link" asp-controller="Account" asp-action="WishLists">WishLists</a></li>
    @if (User.IsInRole("Admin"))
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Admin" asp-action="ListUsers">Users</a></li>
    }
</ul>